CREATE TABLE IF NOT EXISTS orders (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users(id)
);