CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  
  unique(email)
);