export const NameError = {
  QUERY_ERROR: 'Query Error',
  CONNECTION_ERROR: 'Connection Error',
  TRANSACTION_ERROR: 'Transaction Error',
  DUPLICATE_ENTRY_ERROR: 'Duplicate Entry Error',
  CONSTRAINT_ERROR: 'Constraint Error',
  NULL_VALUE_ERROR: 'Null Value Error',
  DATA_INTEGRITY_ERROR: 'Data Integrity Error',
  INVALID_QUERY_ERROR: 'Invalid Query Error',
  TIMEOUT_ERROR: 'Timeout Error',
  UNAVAILABLE_ERROR: 'Unavailable Error',
  LOCK_TIMEOUT_ERROR: 'Lock Timeout Error',
  AUTHENTICATION_ERROR: 'Authentication Error',
  AUTHORIZATION_ERROR: 'Authorization Error',
  ACCESS_DENIED_ERROR: 'Access Denied Error',
  SERVER_ERROR: 'Server Error',
  NETWORK_ERROR: 'Network Error',
  INVALID_STATE_ERROR: 'Invalid State Error',
  INVALID_ARGUMENT_ERROR: 'Invalid Argument Error',
  MISSING_PARAMETER_ERROR: 'Missing Parameter Error',
  UNSUPPORTED_OPERATION_ERROR: 'Unsupported Operation Error',
  PARSE_ERROR: 'Parse Error',
  INVALID_DATA_FORMAT_ERROR: 'Invalid Data Format Error',
  VALIDATION_ERROR: 'Validation Error',
  CONSTRAINT_VIOLATION_ERROR: 'Constraint Violation Error',
  RESOURCE_NOT_FOUND_ERROR: 'Resource Not Found Error',
  UNEXPECTED_RESPONSE_ERROR: 'Unexpected Response Error',
  UNEXPECTED_RESULT_ERROR: 'Unexpected Result Error',
  DATABASE_ERROR: 'Database Error',
  IO_ERROR: 'IO Error',
  FILE_NOT_FOUND_ERROR: 'File Not Found Error',
  CONNECTION_TIMEOUT_ERROR: 'Connection Timeout Error',
  DATA_CONVERSION_ERROR: 'Data Conversion Error',
  UNSUPPORTED_DATABASE_ERROR: 'Unsupported Database Error'
}
